  03 Mathematics
  ==============

  StackExchange: How to calculate modulus of large numbers
  https://stackoverflow.com/questions/2177781/how-to-calculate-modulus-of-large-numbers

  Quora: What are intuitive explanations for determinants?
  https://www.quora.com/What-are-intuitive-explanations-for-determinants

  Quora: How are imaginary numbers useful?
  https://www.quora.com/How-are-imaginary-numbers-useful

  Quora: Are there any examples of causation without correlation?
  https://www.quora.com/Are-there-any-examples-of-causation-without-correlation

  Quora: Are the random numbers generated by a program really random?
  https://www.quora.com/Are-the-random-numbers-generated-by-a-program-really-random

  Quora: Why is e = 2.718281828459…?
  https://www.quora.com/Why-is-e-2-718281828459%E2%80%A6

  Quora: What would happen to f(x) if you transformed it as y=f(1/x)?
  https://www.quora.com/What-would-happen-to-f-x-if-you-transformed-it-as-y-f-1-x

  Quora: Education: An Interactive Multimedia Course of Study
  http://onlinestatbook.com/2/index.html


